### ISSUE TITLE
CocoaPods repo update [timeout]

### ISSUE THREAD

**Issue by ricardopereira** [bitrise-io/build.issues#16]
## Description of the issue

I have a build that get's always aborted because it reaches the timeout.
The build tries to install all CocoaPods of the project.
The problem: _**out-of-date source repos which you can update with `pod repo update`**_ then it tries to update the repo but it takes too much time.

**Abort reason:**
> Timeout: Build took more than 600 seconds. If you need more time for your builds upgrade your subscription plan.

## Environment:

__Where did the issue happen?__

Xcode 7.3.1
OS X 10.11 (El Capitan)

__Which build Step causes the issue and which version of the step?__

cocoapods-install@1.5.7

## Reproducibility

- _Does a "Rebuild" help? (You can trigger a rebuild from the Build's page, by clicking the "Rebuild" button in the top right corner of a finished build)_ : **YES**
- _When did the issue start?_ : **First time setup.**

## Build log

```
Installing cocoapods: 1.1.1
  => gem "install" "cocoapods" "-v" "1.1.1" "--no-document"
  Successfully installed gh_inspector-1.0.2
Successfully installed fourflusher-2.0.1
Successfully installed nanaimo-0.2.3
Successfully installed claide-1.0.1
Successfully installed CFPropertyList-2.3.4
Successfully installed xcodeproj-1.4.1
Successfully installed molinillo-0.5.4
Successfully installed cocoapods-try-1.1.0
Successfully installed cocoapods-trunk-1.1.1
Successfully installed cocoapods-stats-1.0.0
Successfully installed cocoapods-search-1.0.0
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-downloader-1.1.2
Successfully installed cocoapods-deintegrate-1.0.1
Successfully installed cocoapods-core-1.1.1
Successfully installed cocoapods-1.1.1
16 gems installed

Installing Pods
  => pod "_1.1.1_" "--version"
  1.1.1
  => pod "_1.1.1_" "install" "--no-repo-update" "--verbose"
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Pearland`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-PearlandTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-PearlandUITests`: (``)

Finding Podfile changes
  - Alamofire
  - Crashlytics
  - Fabric
  - JGProgressHUD
  - Nimble
  - PremierKit
  - RxSwift
  - SnapKit
  - Stripe
  - TZStackView
  - WSLogger
  - WSReachability
  - WSTagsField
  - p2.OAuth2

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `PremierKit (~> 2.1.5)` required by `Podfile`
- `PremierKit (~> 2.1.5)` required by `Podfile`
- `PremierKit (~> 2.1.5)` required by `Podfile`
- `PremierKit (~> 2.1.5)` required by `Podfile`
- `PremierKit (= 2.1.5)` required by `Podfile.lock`

None of your spec sources contain a spec satisfying the dependencies: `PremierKit (~> 2.1.5), PremierKit (= 2.1.5)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:442:in `handle_resolver_error'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:65:in `rescue in resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:57:in `resolve'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:723:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:721:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:110:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
Command failed with error: exit status 1, retrying without --no-repo-update ...
  => pod "_1.1.1_" "repo" "update"
```

**Comment by viktorbenei** [comment]
Unfortunately that's a side effect of the breaking change in CocoaPods 0.39 <-> 1.0.0 (see: http://blog.cocoapods.org/Sharding/ )

The Xcode 7.3 stack is on CocoaPods 0.39 - you should downgrade to that, to make pod install fast. Or if you want to use CocoaPods 1.0.0, you should use an Xcode 8 stack, those are on CocoaPods 1.x by default.

**Comment by viktorbenei** [comment]
Ohh, and of course, thanks for reporting the issue with including the details, it really helps us a lot as well as others in the future.

I'll close this issue, but if you have any question, feel free to ask!

**Comment by ricardopereira** [comment]
Thanks for the fast reply.
I'm using the Xcode 7.3 stack so how can I setup the step to use the 0.39?

**Comment by viktorbenei** [comment]
Can you please include the full log of the CocoaPods Install step? Asking because the step can get the required CocoaPods version from a couple of sources.

The most likely one is your `Podfile.lock`. If you have that committed into your repo (which you should!) the latest versions of the CocoaPods install step will get the required CocoaPods version from that file - it's at the end of `Podfile.lock`, and it's auto generated when you run `pod install` on your Mac. Of course, you should make sure that you have CocoaPods 0.39 on your Mac, and then run `pod install` and commit the `Podfile.lock`.

Another source, if you have a `Gemfile.lock` in the directory of the `Podfile`. That's less likely, but might be the case. In that case the version of CocoaPods will be read from the `Gemfile.lock`.

**Comment by ricardopereira** [comment]
I have the `Podfile.lock` committed using v1.1.1. Now I have a dilema because if I force the v0.39 in the `Podfile.lock`, then it errors with `[!] Invalid `Podfile` file: undefined method `inherit!' for #<Pod::Podfile:0x007fc6bbd1e820>. Updating CocoaPods might fix the issue.`. I can't change the `Podfile` back to a valid format because the team is already using the v1 of CocoaPods and the project still is in Swift v2.2 (Xcode 7.3) so I can't use the Xcode 8 stack 🤔  Maybe updating the proejct to v2.3 should be enough.

```
+------------------------------------------------------------------------------+
| (2) cocoapods-install@1.5.7                                                  |
+------------------------------------------------------------------------------+
| id: cocoapods-install                                                        |
| version: 1.5.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2016-12-03T06:44:25-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |

Configs:
  * source_root_path: /Users/vagrant/git
  * podfile_path: 
  * system_cocoapods_version: 0.39.0
  * verbose: true

Searching for Podfile
  Found Podfile: /Users/vagrant/git/Podfile

Determining required cocoapods version
  Searching for Gemfile.lock with cocoapods gem
  No Gemfile.lock with cocoapods gem found at: /Users/vagrant/git/Gemfile.lock

  Searching for Podfile.lock
  Found Podfile.lock: /Users/vagrant/git/Podfile.lock
  CocoaPods version: 0.39.0

Installing Pods
  => pod "--version"
  0.39.0
  => pod "install" "--no-repo-update" "--verbose"
  [!] Invalid `Podfile` file: undefined method `inherit!' for #<Pod::Podfile:0x007fc6bbd1e820>. Updating CocoaPods might fix the issue.
```

**Comment by viktorbenei** [comment]
Indeed CocoaPods  0.39 and 1.0 are not compatible, the Gemfile have to be changed.
Swoft 2.3 and Xcode 8 might be an option, but then you'll probably have to update your swift code. 
Apple doesn't make it easy to stick with old tool versions if you work in Swift unfortunately..
